In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in d:\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
import numpy as np

In [7]:
# USE CASES OF PANDAS
# 1. DATA CLEANING
# 2. DATA ANALYSIS
# 3. DATA TRANSFORMATION
# 4. DATA VISUALIZATION
# 5. DATA AGGREGATION
# 6. FILE HANDLING
# 7. DATA FILTERING AND SELECTION
# 8. TIME SERIES ANALYSIS

In [8]:
# PANDAS SERIES

In [9]:
labels = ['a','b','c','d']
my_list = [10,20,30,40]

my_arr = np.array([10,20,30,40])
d = {1:10,2:20,3:30}

In [10]:
pd.Series(my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [13]:
pd.Series(my_arr,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [15]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [17]:
# Pandas Seriesabs
# Definition: A 1D array capable of holding any data type (integers, strings, floats, etc.)
# Visual Representation

# Index    Values
# 0        Apple
# 1        Banana
# 2        Cherry


# Pandas DataFrame

# A 2D table-like data structure that aligns multiple Series objects together using a shared index.

# Visual Representation:

# Index    Fruit      Price
# 0        Apple      1.20
# 1        Banana     0.50
# 2        Cherry     3.00

In [22]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}


df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [23]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]


columns = ['Name','Age','City','Salary']
df = pd.DataFrame(data_list,columns=columns)

In [30]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
# df['Name']
df[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [42]:
# creating a new columns

df["Department"] = ["Sales","HR","Design","Engineering"]

In [43]:
df

    Name  Age      City  Salary   Department
0   John   28  New York   65000        Sales
1   Anna   34     Paris   70000           HR
2  Peter   29    Berlin   62000       Design
3  Linda   42    London   85000  Engineering

In [39]:
# Removing Column

df.drop("Department",axis=1,inplace=True)

# axis = 0 for the horizontal
# axis = 1 for the vertical

In [45]:
df

    Name  Age      City  Salary   Department
0   John   28  New York   65000        Sales
1   Anna   34     Paris   70000           HR
2  Peter   29    Berlin   62000       Design
3  Linda   42    London   85000  Engineering

In [51]:

# Accessing row in the dataframe
df.loc[0]
df.loc[[0,1]]

   Name  Age      City  Salary Department
0  John   28  New York   65000      Sales
1  Anna   34     Paris   70000         HR

In [54]:
# selecting subsets of rows and columns

df.loc[[0,1]][["City","Salary","Department"]]

       City  Salary Department
0  New York   65000      Sales
1     Paris   70000         HR

In [55]:
df

    Name  Age      City  Salary   Department
0   John   28  New York   65000        Sales
1   Anna   34     Paris   70000           HR
2  Peter   29    Berlin   62000       Design
3  Linda   42    London   85000  Engineering

In [56]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [57]:
# conditional selectionabs


df

    Name  Age      City  Salary   Department
0   John   28  New York   65000        Sales
1   Anna   34     Paris   70000           HR
2  Peter   29    Berlin   62000       Design
3  Linda   42    London   85000  Engineering

In [61]:
# select only age > 30 and city is Paris

df[(df["Age"] > 30) & (df["City"] == "Paris")]

   Name  Age   City  Salary Department
1  Anna   34  Paris   70000         HR

In [62]:

# select only age > 30
df[df["Age"] > 30]

    Name  Age    City  Salary   Department
1   Anna   34   Paris   70000           HR
3  Linda   42  London   85000  Engineering

In [63]:
# Missing Data

# Finding Missing data
# Removing Missing Data
# Filling Missing data

In [64]:
# Finding Missing Data

In [65]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}


df = pd.DataFrame(data)

In [68]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [67]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [69]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [70]:
# to check if in any column any Nan value exist

df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [73]:
# Removing Missing Data

# it works on the basis of rows
df.dropna()  # will remove row of null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [72]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [75]:
# Thrushold
df.dropna(thresh=3) # will drop only rows which has less than 3 Non Nan values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [76]:
# Filling the missing data

df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [77]:
df.fillna(0) # filling with zeros

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [78]:
# fillling with different values for different ccolumns

values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [79]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0